# Compute the revenue generated by each customer based on their orders.
# Also, show each customer's revenue as a percentage of total revenue. Sort by customer name.
SELECT
    c.customerName,
    SUM(od.priceEach * od.quantityOrdered)           AS revenue,
    SUM(od.priceEach * od.quantityOrdered) / (
        SELECT
            SUM(od.quantityOrdered * od.priceEach)
        FROM
            orderdetails od
            JOIN classicmodels.orders o ON od.orderNumber = o.orderNumber
                                             ) * 100 AS revenue_percentage
FROM
    customers c
    JOIN orders o ON c.customerNumber = o.customerNumber
    JOIN orderdetails od ON o.orderNumber = od.orderNumber
GROUP BY
    c.customerName
ORDER BY
    c.customerName
