# Compute the profit generated by each customer based on their orders.
# Also, show each customer's profit as a percentage of total profit. Sort by profit descending.
SELECT
    c.customerName,
    SUM(od.quantityOrdered * od.priceEach - od.quantityOrdered * p.buyPrice)           AS profit,
    SUM(od.quantityOrdered * od.priceEach - od.quantityOrdered * p.buyPrice) / (
        SELECT

            SUM(od.quantityOrdered * od.priceEach - od.quantityOrdered * p.buyPrice) AS profit

        FROM
            orders o
            JOIN orderdetails od ON o.orderNumber = od.orderNumber
            JOIN products p ON od.productCode = p.productCode
                                                                               ) * 100 AS profit_percentage
FROM
    customers c
    JOIN orders o ON c.customerNumber = o.customerNumber
    JOIN orderdetails od ON o.orderNumber = od.orderNumber
    JOIN products p ON od.productCode = p.productCode
GROUP BY
    c.customerName
ORDER BY
    profit DESC
