# Compute the profit generated by each product line, sorted by profit descending.
SELECT
    pl.productLine,
    SUM(od.quantityOrdered * od.priceEach - od.quantityOrdered * p.buyPrice) AS profit
FROM
    orderdetails od
    JOIN products p ON od.productCode = p.productCode
    JOIN productlines pl ON p.productLine = pl.productLine
GROUP BY
    pl.productLine
ORDER BY
    profit DESC
